
#Disables certain types. Note that all these configs, like in any other mod, only hide stuff from tabs and disable their recipes
[types]

	[types.wood_type]

		[types.wood_type.domum_ornamentum]
			cactus = true
			cactus_extra = true

		[types.wood_type.ars_nouveau]
			archwood = true

		[types.wood_type.blue_skies]
			crystallized = true
			bluebright = true
			starlit = true
			frostbright = true
			lunar = true
			dusk = true
			maple = true
			comet = true

		[types.wood_type.ecologics]
			flowering_azalea = true
			azalea = true
			coconut = true
			walnut = true

		[types.wood_type.quark]
			azalea = true
			ancient = true
			blossom = true

		[types.wood_type.hexerei]
			mahogany = true
			willow = true
			witch_hazel = true

		[types.wood_type.iceandfire]
			dreadwood = true

		[types.wood_type.twilightforest]
			twilight_oak = true
			canopy = true
			mangrove = true
			dark = true
			time = true
			transformation = true
			mining = true
			sorting = true

		[types.wood_type.cataclysm]
			chorus = true

		[types.wood_type.vinery]
			dark_cherry = true

		[types.wood_type.biomemakeover]
			blighted_balsa = true
			willow = true
			swamp_cypress = true
			ancient_oak = true

		[types.wood_type.swem]
			whitewash = true

	[types.stone_type]

		[types.stone_type.blue_skies]
			polished_brumble = true

		[types.stone_type.naturalist]
			shellstone = true

		[types.stone_type.iceandfire]
			dread_stone = true

		[types.stone_type.biomemakeover]
			dried_peat = true

		[types.stone_type.create]
			cut_granite = true
			cut_diorite = true
			cut_andesite = true
			cut_calcite = true
			cut_dripstone = true
			cut_deepslate = true
			cut_tuff = true
			cut_asurine = true
			cut_crimsite = true
			cut_limestone = true
			cut_ochrum = true
			cut_scoria = true
			cut_scorchia = true
			cut_veridium = true

		[types.stone_type.quark]
			soul_sandstone = true
			permafrost = true
			limestone = true
			jasper = true
			shale = true
			myalite = true

		[types.stone_type.supplementaries]
			ash = true

	[types.leaves_type]

		[types.leaves_type.ecologics]
			coconut = true
			walnut = true

		[types.leaves_type.ars_nouveau]
			blue_archwood = true
			green_archwood = true
			purple_archwood = true
			red_archwood = true

		[types.leaves_type.blue_skies]
			crystallized = true
			crescent_fruit = true
			bluebright = true
			starlit = true
			frostbright = true
			lunar = true
			dusk = true
			maple = true
			comet = true

		[types.leaves_type.twilightforest]
			beanstalk = true
			thorn = true
			twilight_oak = true
			canopy = true
			mangrove = true
			dark = true
			rainbow_oak = true
			time = true
			transformation = true
			mining = true
			sorting = true

		[types.leaves_type.croptopia]
			cinnamon = true

		[types.leaves_type.hexerei]
			mahogany = true
			willow = true
			witch_hazel = true

		[types.leaves_type.dthexerei]
			mahogany = true
			willow = true
			witch_hazel = true

		[types.leaves_type.dttwilightforest]
			canopy = true
			dark_forest_birch = true
			dark_forest_oak = true
			darkwood = true
			mangrove = true
			mining = true
			rainbow_oak = true
			robust_twilight_oak = true
			sorting = true
			time = true
			transformation = true
			twilight_oak = true

		[types.leaves_type.culturaldelights]
			avocado = true
			fruiting_avocado = true

		[types.leaves_type.vinery]
			grapevine = true
			dark_cherry = true
			apple = true

		[types.leaves_type.biomemakeover]
			blighted_balsa = true
			willow = true
			swamp_cypress = true
			ancient_oak = true

		[types.leaves_type.dtarsnouveau]
			blue_archwood = true
			green_archwood = true
			purple_archwood = true
			red_archwood = true

		[types.leaves_type.dtterralith]
			acacia_amethyst = true
			acacia_bush = true
			acacia_conifer = true
			acacia_deciduous = true
			acacia_kapok = true
			acacia_poplar = true
			acacia_sparse = true
			acacia_twiglet = true
			acacia_windswept = true
			azalea_bush = true
			azalea_canopy = true
			azalea_ebony = true
			azalea_mahogany = true
			azalea_mangrove = true
			azalea_oasis = true
			birch_conifer = true
			birch_poplar = true
			birch_scruffy = true
			birch_scruffy_conifer = true
			birch_short_conifer = true
			birch_sparse = true
			birch_twilight = true
			birch_windswept = true
			cherry_bush = true
			dark_oak_ancient = true
			dark_oak_ancient_mirage = true
			dark_oak_blue_conifer = true
			dark_oak_canopy = true
			dark_oak_canopy_mirage = true
			dark_oak_jacaranda = true
			dark_oak_maple = true
			dark_oak_orange_conifer = true
			dark_oak_red_azalea = true
			dark_oak_red_conifer = true
			dark_oak_red_maple = true
			dark_oak_sakura = true
			dark_oak_sakura_bush = true
			dark_oak_wide = true
			flowering_azalea_canopy = true
			flowering_azalea_mahogany = true
			flowering_azalea_mangrove = true
			flowering_azalea_oasis = true
			jungle_jacaranda = true
			jungle_sakura = true
			jungle_sparse = true
			jungle_windswept = true
			mangrove_scruffy = true
			mangrove_sparse = true
			oak_conifer = true
			oak_kapok = true
			oak_scruffy = true
			oak_scruffy_tall_conifer = true
			oak_sparse = true
			oak_tall_conifer = true
			oak_twiglet = true
			oak_twilight = true
			oak_yellow_conifer = true
			spruce_bush = true
			spruce_moonlight = true
			spruce_poplar = true
			spruce_round = true
			spruce_short_conifer = true
			spruce_sparse = true
			spruce_tall_conifer = true
			spruce_twiglet = true
			tall_dark_oak = true

		[types.leaves_type.quark]
			ancient = true
			blue_blossom = true
			lavender_blossom = true
			orange_blossom = true
			yellow_blossom = true
			red_blossom = true

#Disables specific entries
[entries]

	[entries.wood_type]

		[entries.wood_type.cfm]
			stripped_kitchen_sink_light = true
			table = true
			coffee_table = true
			park_bench = true
			stripped_kitchen_counter = true
			stripped_bedside_cabinet = true
			desk_cabinet = true
			upgraded_fence = true
			kitchen_counter = true
			upgraded_gate = true
			stripped_park_bench = true
			cabinet = true
			mail_box = true
			crate = true
			chair = true
			stripped_mail_box = true
			stripped_blinds = true
			bedside_cabinet = true
			stripped_upgraded_fence = true
			stripped_cabinet = true
			kitchen_drawer = true
			desk = true
			stripped_kitchen_drawer = true
			kitchen_sink_dark = true
			stripped_desk_cabinet = true
			stripped_table = true
			blinds = true
			stripped_chair = true
			stripped_kitchen_sink_dark = true
			stripped_desk = true
			kitchen_sink_light = true
			stripped_coffee_table = true
			stripped_crate = true
			stripped_upgraded_gate = true

		[entries.wood_type.handcrafted]
			counter = true
			corner_trim = true
			fancy_bed = true
			desk = true
			dining_bench = true
			drawer = true
			side_table = true
			couch = true
			table = true
			chair = true
			shelf = true
			cupboard = true
			bench = true
			pillar_trim = true
			nightstand = true

		[entries.wood_type.mcwfurnitures]
			stripped_glass_table = true
			stripped_desk = true
			end_table = true
			stool_chair = true
			stripped_lower_triple_drawer = true
			stripped_drawer_counter = true
			bookshelf_drawer = true
			double_drawer = true
			stripped_coffee_table = true
			stripped_counter = true
			stripped_striped_chair = true
			covered_desk = true
			stripped_stool_chair = true
			stripped_modern_wardrobe = true
			cupboard_counter = true
			stripped_covered_desk = true
			coffee_table = true
			glass_table = true
			stripped_cupboard_counter = true
			stripped_triple_drawer = true
			stripped_chair = true
			stripped_double_drawer_counter = true
			stripped_modern_desk = true
			stripped_bookshelf_cupboard = true
			modern_wardrobe = true
			lower_bookshelf_drawer = true
			striped_chair = true
			stripped_large_drawer = true
			wardrobe = true
			modern_desk = true
			stripped_lower_bookshelf_drawer = true
			stripped_end_table = true
			drawer = true
			stripped_bookshelf_drawer = true
			stripped_bookshelf = true
			modern_chair = true
			chair = true
			stripped_table = true
			double_drawer_counter = true
			drawer_counter = true
			counter = true
			stripped_modern_chair = true
			bookshelf_cupboard = true
			table = true
			desk = true
			stripped_double_wardrobe = true
			stripped_double_drawer = true
			triple_drawer = true
			lower_triple_drawer = true
			bookshelf = true
			stripped_wardrobe = true
			large_drawer = true
			double_wardrobe = true
			stripped_drawer = true

		[entries.wood_type.quark]
			vertical_planks = true
			ladder = true
			post = true
			trapped_chest = true
			chest = true
			hollow_log = true
			bookshelf = true
			stripped_post = true

		[entries.wood_type.twilightforest]
			banister = true
			hollow_log_climbable = true
			hollow_log_horizontal = true
			hollow_log_vertical = true

		[entries.wood_type.another_furniture]
			flower_box = true
			shutter = true
			drawer = true
			shelf = true
			bench = true
			table = true
			chair = true

		[entries.wood_type.decorative_blocks]
			seat = true
			palisade = true
			beam = true
			support = true

		[entries.wood_type.farmersdelight]
			cabinet = true

		[entries.wood_type.mcwlights]
			tiki_torch = true
			soul_tiki_torch = true
			ceiling_fan_light = true

		[entries.wood_type.storagedrawers]
			full_drawers_2 = true
			full_drawers_4 = true
			full_drawers_1 = true
			half_drawers_1 = true
			half_drawers_4 = true
			half_drawers_2 = true
			trim = true

		[entries.wood_type.create]
			window_pane = true
			window = true

	[entries.leaves_type]

		[entries.leaves_type.quark]
			hedge = true
			leaf_carpet = true

		[entries.leaves_type.cfm]
			hedge = true

